### PR TITLE
Replace hevea with pandoc

### PR DESCRIPTION
**Pull request by klingtnet**
This pull request replaces the hevea Makefile target with a simple [pandoc](https://pandoc.org/)  target that generates an HTML5 version of the book.
In order to have scalable graphics in the HTML version the PDF figures were converted to SVG files.
Also, the `latexonly` file was inlined and `htmlonly` which is now redundant was removed.
I was not sure if the EPS files are still required, if not I could remove them in the PR as well.

### CODE REVIEW

**Comment by klingtnet** [comment]
Closes #39

**Comment by klingtnet** [comment]
I added an additional target that uses pandoc to generate an `epub` version of the book.

**Comment by klingtnet** [comment]
Those geometry overrides should be omitted in the source file used to generate HTML/epub files because they will be inserted as is in the output file: https://github.com/klingtnet/ThinkDSP/blob/b73b0d8a6a59e2453e10003668d3274e06f0f895/book/book.tex#L98-L110

**Comment by AllenDowney** [comment]
Thanks very much for your work on this.  It's hard for me to merge this as a PR because it does so many things at once.  To transition from hevea to pandoc, I would need to make incremental changes and test along the way.  I'm afraid I am stuck with hevea for now because I don't have time to rebuild my tool chain.  Thank you though!

**Pull request closed without merging**
