### PR TITLE
Add 'hevea.sty'

### PR DESCRIPTION
**Pull request by usmanayubsh**
Without it, compilation of source fails with the following output:

`./book.tex:26: LaTeX Error: File 'hevea.sty' not found. [\usepackage]`

The same error has been reported [here](http://latex-community.org/forum/viewtopic.php?f=5&t=8635) too.

### CODE REVIEW

**Comment by AllenDowney** [comment]
Putting hevea.sty in this directory might not be the best solution -- ideally, hevea should be installed.

Or even better, latex should check for hevea and use it if it is available.  I won't have a chance to work on that for a while, though.

**Comment by AllenDowney** [comment]
But in the meantime, it seems like including hevea.sty is the way to go.  Thanks!

**Comment by usmanayubsh** [comment]
Sir, I totally agree with you, it's a dirty and temporary work-around. But `hevea.sty` doesn't come with `texlive-latex-extra` (as suggested for download in comments of `thinkdsp.tex`) and thus creates problem for Ubuntu users like me. Thanks!

**Comment by AllenDowney** [comment]
Ok, dirty workaround it is, then!

**Pull request merged**
