### PR TITLE
run with Py3. OK.

### PR DESCRIPTION
**Pull request by hisakato**
👍

### CODE REVIEW

**Comment by hisakato** [comment]
Sorry. This was a wrong pull request.

**Comment by AllenDowney** [comment]
No problem.  Is there something I should change here to make it compatible with Python 3?

**Comment by hisakato** [comment]
I found a Python 3 incompatibility in Think Stat 2. I will report to you there.

**Comment by AllenDowney** [comment]
Got it.  Thanks!

**Pull request closed without merging**
